[package]
name = "ada-url"
version = "0.1.0"
edition = "2021"


[[bench]]
name = "parse"
path = "bench/parse.rs"

[dependencies]
anyhow = "1"
thiserror = "1"

[dev-dependencies]
url = "2"

[build-dependencies]
cc = "1"